default_config:
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - "172.27.0.0/24"
frontend:
  themes: !include_dir_merge_named themes
group: !include groups.yaml
light: !include lights.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  external_url: https://hass.coyotesin.space
  media_dirs:
    music: /media/music
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
zone: !include zones.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
lock: !include locks.yaml
input_text: !include input_texts.yaml
rest_command: !include rest_commands.yaml
zeroconf:
media_player:
  - platform: vlc_telnet
    name: VLC
    host: coyotoyden.yapspace
    port: 4212
    password: "vlcplayer"
media_extractor:
recorder:
  db_url: !secret postgres_url
  exclude:
    entity_globs:
      - sensor.docker_*
      - sensor.weather_*
    domains:
      - weather
logbook:
  exclude:
    entity_globs:
      - sensor.docker_*
      - sensor.weather_*
    domains:
      - weather
logger:
  default: warn
  # logs:
  #   homeassistant.components.tplink: debug
  #   pyHS100: debug
  # logs:
  #   homeassistant.components.pyscript: debug
  #   pyscript: debug
  #   custom_components.pyscript: debug
# influxdb:
#   api_version: 1
#   host: 192.168.1.10
#   port: 18086
#   username: !env_var INFLUXDB_USER
#   password: !env_var INFLUXDB_USER_PASSWORD
#   database: !env_var INFLUXDB_DB
#   exclude:
#     domains:
#       - media_player
#       - vacuum
#       - light
#       - switch
#     entity_globs:
#       - sensor.docker_*
#       - sensor.weather_*

tts:
  # - platform: google_translate
  # - platform: google_cloud
  #   key_file: !secret google_cloud_keyfile
  #   language: en-US
  #   gender: female
alarm_control_panel:
  - platform: manual
ifttt:
  key: !secret ifttt_key
habitica:
  - api_user: !secret habitica_user
    api_key: !secret habitica_token
conversation:
telegram_bot:
  - platform: webhooks
    allowed_chat_ids:
      - 54326855
    api_key: !secret telegram_bot_api_key
    trusted_networks:
      - 149.154.160.0/20
      - 91.108.4.0/22
      - 127.0.0.1/32
notify: !include notifiers.yaml
stream:
ffmpeg:
camera: !include cameras.yaml
#wemo:
#  discovery: false
#  static:
#    - sw-wax-melter.yapspace
#    - sw-tv-speakers.yapspace
# tplink:
#   discovery: false
#   switch:
#     - host: sw-desk-lamp.yapspace
#     - host: sw-living-room-fan.yapspace
#     - host: sw-bedroom-fan.yapspace
#     - host: sw-dehumidifier.yapspace
#     - host: sw-outside-front-lights.yapspace
# eufy:
#   devices:
#     - address: sw-eufy1.yapspace
#       access_token: !secret eufy1
#       type: T1202
#       name: eufy1
#     - address: sw-eufy2.yapspace
#       access_token: !secret eufy2
#       type: T1202
#       name: eufy2
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

# HACS plugin configs

eufy_vacuum:
  devices:
    - name: Robovac
      address: 192.168.1.25
      access_token: !secret eufyvac_token
      id: !secret eufyvac_devid
      type: T2118

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

circadian_lighting:

pyscript:
  allow_all_imports: true
  apps:
    tpwalf:
      - service_name: illuminate_walf
        username: !env_var WALF_TPLINK_USERNAME
        password: !env_var WALF_TPLINK_PASSWORD
