- platform: switch
  name: Deck Lights
  entity_id: switch.outdoor_switch
- platform: switch
  entity_id: switch.desk_lamp
  name: Desk Lamp
- platform: group
  name: Office Lights
  entities:
    - light.office_overhead
    - light.desk_lamp
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_ceiling
    - light.living_room_side_lamp
- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_1
    - light.kitchen_2
    - light.kitchen_3
    - light.kitchen_4
    - light.kitchen_counter_light
- platform: group
  name: Lights
  entities:
    - light.kitchen_lights
    - light.living_room_lights
    - light.office_lights
    - light.deck_lights
    - light.bedroom_lights
    - light.hallway_light
    - light.bulletin_board
    - light.tv_bias_strip
- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_table_lamp
    - light.bedroom_overhead